# Generated by Django 6.0.1 on 2026-01-26 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('expression_orale', 'Expression Orale'), ('mathematiques', 'Mathématiques'), ('sciences', "Sciences d'Observation"), ('ecm', 'Éducation Civique et Morale'), ('eps', 'Éducation Physique et Sportive'), ('arts', 'Arts et Culture'), ('app', 'Activités Pratiques de Production')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, help_text="URL de l'image pour l'accueil", null=True)),
                ('audio_intro_url', models.URLField(blank=True, help_text="URL audio d'introduction", null=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
            ],
        ),
        migrations.CreateModel(
            name='ProfilEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('cp1', 'CP1'), ('cp2', 'CP2'), ('ce1', 'CE1'), ('ce2', 'CE2'), ('cm1', 'CM1'), ('cm2', 'CM2'), ('6e', '6ème'), ('5e', '5ème'), ('4e', '4ème'), ('3e', '3ème')], max_length=10)),
                ('points', models.IntegerField(default=0)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_eleve', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('cp1', 'CP1'), ('cp2', 'CP2'), ('ce1', 'CE1'), ('ce2', 'CE2'), ('cm1', 'CM1'), ('cm2', 'CM2'), ('6e', '6ème'), ('5e', '5ème'), ('4e', '4ème'), ('3e', '3ème')], max_length=10)),
                ('titre', models.CharField(max_length=200)),
                ('resume', models.TextField(help_text='Résumé du contenu du thème')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, help_text="URL audio d'explication", null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.matiere')),
            ],
            options={
                'ordering': ['matiere', 'classe', 'ordre'],
                'unique_together': {('matiere', 'classe', 'titre')},
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_exercice', models.CharField(choices=[('choix_multiple', 'Choix Multiple (Images)'), ('drag_drop', 'Drag & Drop'), ('calcul', 'Calcul'), ('observation', 'Observation')], max_length=20)),
                ('question', models.TextField(help_text='Question textuelle')),
                ('question_image_url', models.URLField(blank=True, help_text='Image de la question', null=True)),
                ('question_audio_url', models.URLField(blank=True, help_text='Audio de la question', null=True)),
                ('options_images', models.JSONField(blank=True, default=list, help_text="Liste d'URLs d'images pour les options (CP1/CP2)")),
                ('options_text', models.JSONField(blank=True, default=list, help_text='Liste de textes pour les options')),
                ('correct_index', models.IntegerField(help_text='Index de la réponse correcte (0-based)')),
                ('feedback_success_text', models.TextField(default='Bravo ! Excellente réponse !')),
                ('feedback_success_audio_url', models.URLField(blank=True, null=True)),
                ('feedback_fail_text', models.TextField(default='Pas bon, essaie encore !')),
                ('feedback_fail_audio_url', models.URLField(blank=True, null=True)),
                ('difficulte', models.IntegerField(default=1, help_text='1=Facile, 2=Moyen, 3=Difficile')),
                ('points_recompense', models.IntegerField(default=10)),
                ('genere_par_ia', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='core.topic')),
            ],
            options={
                'ordering': ['topic', 'difficulte', 'date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_index', models.IntegerField(help_text='Index de la réponse choisie')),
                ('est_correcte', models.BooleanField()),
                ('score', models.IntegerField(default=0, help_text='Points obtenus')),
                ('temps_reponse', models.IntegerField(blank=True, help_text='Temps en secondes', null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='core.profileleve')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='core.exercice')),
            ],
            options={
                'ordering': ['-date_soumission'],
                'indexes': [models.Index(fields=['eleve', 'date_soumission'], name='core_soumis_eleve_i_a29a24_idx'), models.Index(fields=['exercice', 'est_correcte'], name='core_soumis_exercic_b0f249_idx')],
            },
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_total', models.IntegerField(default=0)),
                ('exercices_reussis', models.IntegerField(default=0)),
                ('exercices_total', models.IntegerField(default=0)),
                ('erreurs_consecutives', models.IntegerField(default=0, help_text='Pour adaptation CP1/CP2')),
                ('date_derniere_activite', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='core.profileleve')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='core.topic')),
            ],
            options={
                'ordering': ['-date_derniere_activite'],
                'unique_together': {('eleve', 'topic')},
            },
        ),
    ]
