# Generated by Django 6.0.1 on 2026-02-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='nom',
            field=models.CharField(choices=[('expression_orale', 'Expression Orale'), ('mathematiques', 'Mathématiques'), ('sciences', "Sciences d'Observation"), ('histoire', 'Histoire'), ('geographie', 'Géographie'), ('ecm', 'Éducation Civique et Morale'), ('eps', 'Éducation Physique et Sportive'), ('arts', 'Arts et Culture'), ('app', 'Activités Pratiques de Production')], max_length=50, unique=True),
        ),
    ]
