# Generated by Django 6.0.1 on 2026-02-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_matiere_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='contenu_cours',
            field=models.TextField(blank=True, help_text='Contenu détaillé du cours (généré par IA)', null=True),
        ),
    ]
