# Generated by Django 6.0.1 on 2026-02-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_topic_contenu_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileleve',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profileleve',
            name='classe',
            field=models.CharField(choices=[('cp1', 'CP1'), ('cp2', 'CP2'), ('ce1', 'CE1'), ('ce2', 'CE2'), ('cm1', 'CM1'), ('cm2', 'CM2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='topic',
            name='classe',
            field=models.CharField(choices=[('cp1', 'CP1'), ('cp2', 'CP2'), ('ce1', 'CE1'), ('ce2', 'CE2'), ('cm1', 'CM1'), ('cm2', 'CM2')], max_length=10),
        ),
    ]
