# Generated by Django 6.0.2 on 2026-02-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_matiere_nom_alter_profileleve_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='nom',
            field=models.CharField(choices=[('expression_orale', 'Expression Orale'), ('mathematiques', 'Mathématiques'), ('sciences', "Sciences d'Observation"), ('histoire', 'Histoire'), ('geographie', 'Géographie'), ('ecm', 'Éducation Civique et Morale'), ('eps', 'Éducation Physique et Sportive'), ('arts', 'Arts et Culture'), ('app', 'Activités Pratiques de Production'), ('anglais', 'Anglais'), ('svt', 'SVT'), ('sciences_physiques', 'Sciences Physiques'), ('philosophie', 'Philosophie')], max_length=50, unique=True),
        ),
    ]
