# Generated by Django 6.0.1 on 2026-02-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_matiere_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='nom',
            field=models.CharField(choices=[('francais', 'Français'), ('lecture', 'Lecture'), ('litterature', 'Littérature'), ('ecriture', 'Écriture'), ('grammaire', 'Grammaire'), ('conjugaison', 'Conjugaison'), ('orthographe', 'Orthographe'), ('vocabulaire', 'Vocabulaire'), ('expression_orale', 'Expression Orale'), ('expression_ecrite', 'Expression Écrite'), ('mathematiques', 'Mathématiques'), ('arithmetique', 'Arithmétique'), ('geometrie', 'Géométrie'), ('systeme_metrique', 'Système Métrique'), ('sciences', 'Sciences'), ('exercices_sensoriels', 'Exercices Sensoriels'), ('exercices_observation', "Exercices d'Observation"), ('histoire', 'Histoire'), ('geographie', 'Géographie'), ('ecm', 'Éducation Civique et Morale'), ('aec', "Activités d'Expression et de Création (AEC)"), ('arts', 'Arts et Culture'), ('anglais', 'Anglais'), ('svt', 'SVT'), ('physique_chimie', 'Physique-Chimie'), ('philosophie', 'Philosophie'), ('tic', 'Informatique (TIC)')], max_length=50, unique=True),
        ),
    ]
